### ISSUE TITLE
Support pending transactions

### ISSUE THREAD

**Issue by chaoxu** [simplefin/simplefin.github.com#16]
I've just started using this tool. 

I wish the protocol can support the following:
 - pending transactions, in fact the main purpose of using this is to get pending transactions, which almost never show up if I download ofx files.
 - paging: I see that the limit on number of transactions is 1000. This seems to be insufficient for certain purposes: even a single day, there can be more than 1000 transactions. So having paging support is crucial.

**Comment by iffy** [comment]
I've split this into two issues. Pending transactions is planned, so I expect it will happen sometime soon.

**Comment by 1amtimon** [comment]
> I've split this into two issues. Pending transactions is planned, so I expect it will happen sometime soon.

Do you know when PENDING transactions will be included?

**Comment by iffy** [comment]
Later today

**Comment by meonkeys** [comment]
Are [pending AUTH transactions](https://en.wikipedia.org/wiki/Authorization_hold) automatically removed? Like, when a hotel puts $500 on your credit card just in case you raid the minibar at 2am.

**Comment by CodeWithCJ** [comment]
I delete PENDING transaction every day and insert only the new ones. This way they get purged if it falls off from the credit card.
